# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# markdown processing
markdown: kramdown

# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: "https://mlangues64.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# site settings
title: Association Morlanaise Langues et Culture
email: mlangues64@gmail.com
name: M'Langues
description: >- # this means to ignore newlines until "baseurl:"
  L'association Morlanaise Langues et Culture a pour objectif la promotion
  des langues et de la culture. Elle propose des activités à Morlaàs pour
  enfants et adultes.

# Jumbotron
home_title: M'Langues
home_subtitle: Association Morlanaise Langues et Culture

# in footer
contact:
    url: /contact
    title: Nous contacter
address: 62 rue Bourgneuf, 64160 Morlaàs

# Google analytics
google_analytics: UA-129498792-1

# Social links => SEO plugins
github_username:  mlangues64
logo: "/assets/img/logo_h.svg"
navbar_logo: "/assets/img/logo_h.svg"
favicon: "/assets/favicon/favicon.ico"
facebook_username: MLangues
facebook:
  publisher: MLangues
social:
    name: M'Langues
    links:
        - https://www.facebook.com/MLangues
        - https://github.com/mlangues64
lang: fr_FR


# paginator
# paginate: 3
# paginate_path: /actualites/page:num
# permalink: /actualites/:title

# navigation
# ----------
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
    - activites.md
    - actualites.md
    - contact.md
    # - about.md

# If you want to link specific pages in your footer, uncomment this
# and add the path to the pages in order as they should show up
footer_pages:
    - mention_legale.md
    - confidentialite.md
    - reglement.md

# Build settings
# --------------
plugins:
  # - jekyll-feed
  - jekyll-sitemap
  # - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
